services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=aluno
      - MYSQL_DATABASE=haunter_store
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    image: backend-test
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://root:aluno@db:3306/haunter_store
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=aluno
      - DB_NAME=haunter_store
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    restart: unless-stopped

  mobile:
    build: ./mobile
    ports:
      - "8082:8081"
    depends_on:
      - backend
    environment:
      - API_URL=http://192.168.56.1:4000
    restart: unless-stopped

volumes:
  mysql_data: